Medium.create(name: "Episode I: The Phantom Menace", year: 1999)
Medium.create(name: "Episode II: Attack of the Clones", year: 2002)
Medium.create(name: "Episode III: Revenge of the Sith", year: 2005)
Medium.create(name: "Episode IV: A New Hope", year: 1977)
Medium.create(name: "Episode V: The Empire Strikes Back", year: 1980)
Medium.create(name: "Episode VI: Return of the Jedi", year: 1983)
Medium.create(name: "Episode VII: The Force Awakens", year: 2015)
Medium.create(name: "Episode VIII: The Last Jedi", year: 2017)
Medium.create(name: "Rogue One: A Star Wars Story", year: 2016)
